config/routes.rb
Rails.application.routes.draw do #  root 'welcome#index'
  root 'static_pages#home'

  get 'guests/not_linked', to: 'guests#guests_not_linked'
  get 'guests/linked', to: 'guests#guests_linked'
  get 'guests/responded', to: 'static_pages#guests_responded'
  get 'guests/export', to: 'guests#export'
  get 'guests/browse_file', to: 'guests#browse_file'
  get 'rsvps/replycards-pdf', to: 'rsvps#replycards_pdf'
  get 'rsvps/:code/replycard', to: 'rsvps#replycard', as: :replycard
  post 'guests/import', to: 'guests#import'
  post 'rsvps/search', to: 'rsvps#search'
  patch 'guests/generate_rsvp', to: 'guests#create_rsvp_code_for_guests'
  patch 'guests/unlink_guests', to: 'guests#unlink_guests'

  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :rsvps, param: :code do
    match 'guests/edit', to: 'guests#edit_all', as: :edit_guests, via: :get
    match 'guests/edit', to: 'guests#update_all', as: :update_guests, via: :patch
    resources :guests
  end

  resources :events
  resources :guests
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @guest = Guest.new
    @rsvp = Rsvp.new
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/guests_responded.html.erb
<div class='jumbotron'>
  <h3>Thank you for your response</h3>
</div>

app/views/static_pages/home.html.erb
<div id=formcontainer class='jumbotron'>
<%= image_tag 'replycardtitle.png', alt: 'Reply Card', class: 'subheading' %>
<%= form_tag rsvps_search_path, class: 'form-horizontal' do %>
  <hr>
  <div class='form-group'>
    <%= label_tag :lastname, 'Lastname' %>
    <%= text_field_tag :lastname, params[:lastname], placeholder: "Enter your lastname", class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= label_tag :code, 'RSVP Code' %>
    <%= text_field_tag :code, params[:code], placeholder: "Enter your RSVP Code", class: 'form-control' %>
  </div>
  <hr>
  <div class='form-group submit-area'>
    <%= submit_tag 'Proceed to RSVP', :name => nil, class: 'btn btn-default' %>
  </div>
<% end %>
</div>