config/routes.rb
Rails.application.routes.draw do #  root 'welcome#index'
  root 'static_pages#home'

  get 'guests/not_linked', to: 'guests#guests_not_linked'
  get 'guests/linked', to: 'guests#guests_linked'
  get 'guests/responded', to: 'static_pages#guests_responded'
  get 'guests/export', to: 'guests#export'
  get 'guests/browse_file', to: 'guests#browse_file'
  get 'rsvps/replycards-pdf', to: 'rsvps#replycards_pdf'
  get 'rsvps/:code/replycard', to: 'rsvps#replycard', as: :replycard
  post 'guests/import', to: 'guests#import'
  post 'rsvps/search', to: 'rsvps#search'
  patch 'guests/generate_rsvp', to: 'guests#create_rsvp_code_for_guests'
  patch 'guests/unlink_guests', to: 'guests#unlink_guests'

  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :rsvps, param: :code do
    match 'guests/edit', to: 'guests#edit_all', as: :edit_guests, via: :get
    match 'guests/edit', to: 'guests#update_all', as: :update_guests, via: :patch
    resources :guests
  end

  resources :events
  resources :guests
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  attr_accessor :code_search_text

  validates :lastname, presence: true

  belongs_to :event
  belongs_to :rsvp

  scope :by_rsvp,
        -> (code) { where(rsvp: Rsvp.find_by(code: code.upcase)) }

  scope :match_code_and_lastname,
        -> (code, lastname) { by_rsvp(code.upcase).where(lastname: lastname.titleize) }

  scope :no_rsvp, -> { where(rsvp: nil) }
  scope :has_rsvp, -> { where.not(rsvp: nil) }
  scope :attending, -> { where(attending: true) }
  scope :not_attending, -> { responded.where(attending: false) }
  scope :responded, -> { where(responded: true) }
  scope :not_responded, -> { where(responded: false) }

  def self.to_csv
    CSV.generate do |csv|
      csv << ['lastname', 'firstname', 'rsvp-code', 'dietaryreq', 'attending', 'responded']
      all.each do |guest|
        code = guest.rsvp.nil? ? '' : guest.rsvp.code
        csv << [guest.lastname, guest.firstname, code, guest.dietaryreq, guest.attending, guest.responded]
      end
    end
  end

  def self.import_from_csv(csv)
    valid_columns = %w(lastname firstname rsvp-code dietaryreq attending responded)
    rows_to_add = []

    CSV.parse(csv, headers: true) do |row|
      row_to_add = row.to_hash.slice(*valid_columns)
      rows_to_add << row.to_hash.slice(*valid_columns) if row_to_add.count > 0
    end

    rows_to_add
  end

  def self.create_from_csv(file)
    return false if file.blank?

    csv = File.read(file.path)
    imported_guests = Guest.import_from_csv(csv)
    guests_success = []
    imported_guests.each do |g|
      g_success = create_guest_with_rsvp_code g
      guests_success << g_success unless g_success.nil?
    end

    guests_success.count == imported_guests.count
  end

  def self.create_guest_with_rsvp_code(guesthash)
    gr = Guest.find_or_initialize_by(firstname: guesthash['firstname'],
                                     lastname: guesthash['lastname'])
    gr.rsvp_id = Rsvp.find_or_create_by(code: guesthash['rsvp-code']).id if gr.rsvp_id.nil?
    gr = set_extra_attributes(guesthash, gr)
    gr.save
    gr.valid? ? gr : nil
  end

  def self.set_extra_attributes(guesthash, gr)
    gr.dietaryreq = guesthash['dietaryreq']
    gr.attending = guesthash['attending']
    gr.responded = guesthash['responded']
    gr
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :logged_in_user, except: [:update_all, :edit_all]
  before_action :set_guest, only: [:show, :edit, :update, :destroy]
  before_action :set_guests_from_rsvp, only: [:edit_all]

  # GET /guest/export
  def export
    send_data Guest.to_csv, filename: 'guests.csv'
  end

  # GET /post/prepare_import
  def browsefile
  end

  # POST /guest/import
  def import
    respond_to do |format|
      valid = Guest.create_from_csv params[:file]
      message = valid ? 'File was successfully imported.' :
                        'There were rows not added from csv file'
      type = valid ? :success : :warning
      format.html { redirect guests_path, message, type }
    end
  end

  # GET /guests/not_linked
  def guests_not_linked
    @guests = Guest.no_rsvp
  end

  # GET /guests/linked
  def guests_linked
    @guests = Guest.has_rsvp
  end

  # PATCH /guests/generate_rsvp
  def create_rsvp_code_for_guests
    respond_to do |format|
      if link_guests_to_rsvp_code
        message = 'Successfully created RSVP code for guests'
        format.html { redirect guests_not_linked_path, message, :success }
      else
        message = 'Couldn\'t link the guests to an RSVP code'
        format.html { redirect guests_not_linked_path, message, :warning }
      end
    end
  end

  # PATCH /guests/unlink_guests
  def unlink_guests
    respond_to do |format|
      if remove_rsvp_code_from_guests
        message = 'Successfully removed RSVP from guests'
        format.html { redirect guests_linked_path, message, :success }
      else
        message = 'Couldn\'t remove RSVP code the guests'
        format.html { redirect guests_linked_path, message, :warning }
      end
    end
  end

  # PATCH /rsvps/:rsvp/guests/edit
  def update_all
    respond_to do |format|
      if process_update_all
        format.html { redirect_to guests_responded_path }
        format.json { render guests_responded_path, status: :ok }
      else
        format.html { render :edit_all }
        format.json { render json: guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /rsvps/:rsvp/guests/edit
  def edit_all
  end

  # GET /guests
  # GET /guests.json
  def index
    if !params[:rsvp_code].blank?
      rsvp_code = params[:rsvp_code]
      @guests = Guest.by_rsvp(rsvp_code)
    else
      @guests = Guest.all
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest = Guest.find(params[:id])
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def process_update_all
    guests_params_hash = guests_params

    @guests = Guest.where(id: guests_params_hash.keys)
    @rsvp_code = params.require(:rsvp_code)

    validate_rsvp_with_guests && Guest.update(guests_params_hash.keys,
                                              guests_params_hash.values)
  end

  def set_guests_from_rsvp
    verified_guest = Guest.match_code_and_lastname(params[:rsvp_code],
                                                   params[:lastname]).first
    if verified_guest && verified_guest.responded
      redirect root_url, "It looks like you've already responded to our RSVP", :warning
    elsif verified_guest
      @guests = Guest.by_rsvp(params[:rsvp_code])
    else
      redirect root_url, "We can't find a match for the lastname and RSVP Code", :warning
    end
  end

  def redirect(url, message, flash_type)
    flash[flash_type] = message
    redirect_to url
  end

  def guests_params
    g_prms_prmt = {}

    params.require(:guests).each do |id, guest_p|
      g_prms_prmt[id] = guest_p.permit(:firstname,
                                       :lastname,
                                       :dietaryreq,
                                       :attending,
                                       :responded)
    end

    g_prms_prmt
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_guest
    @guest = Guest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def guest_params
    params.require(:guest).permit(:firstname,
                                  :lastname,
                                  :dietaryreq,
                                  :attending,
                                  :responded)
  end

  # let's validate that the guests are actually part of the rsvp code given
  def validate_rsvp_with_guests
    @guests.by_rsvp(@rsvp_code).count == Guest.by_rsvp(@rsvp_code).count
  end

  # Get the list of selected guests from the guest link list
  def selected_guests_from_list
    guest_ids = []

    params.require(:guests).each do |id, guest_p|
      selected = guest_p.permit(:selected)[:selected]
      guest_ids << id if selected == '1'
    end

    Guest.where(id: guest_ids)
  end

  # Links guests to rsvp code
  def link_guests_to_rsvp_code
    guests = selected_guests_from_list
    return unless guests.any? && guests.has_rsvp.empty?
    rsvp = Rsvp.generate_rsvp
    guests.update_all(rsvp_id: rsvp.id)
  end

  # Unlink guests to rsvp code
  def remove_rsvp_code_from_guests
    guests = selected_guests_from_list
    return unless guests.any? && guests.no_rsvp.empty?
    guests.update_all(rsvp_id: nil)
  end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
	<% if @guest.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>
			<ul>
			<% @guest.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :firstname %><br>
		<%= f.text_field :firstname %>
	</div>
	<div class="field">
		<%= f.label :lastname %><br>
		<%= f.text_field :lastname %>
	</div>
	<div class="field">
		<%= f.label :dietaryreq %><br>
		<%= f.text_area :dietaryreq %>
	</div>
	<div class="field">
		<%= f.label :attending %><br>
		<%= f.check_box :attending %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/guests/_form_edit_all.html.erb
<div class='jumbotron'>
<%= image_tag 'replycardtitle.png', class: 'subheading' %>

<%= form_tag(rsvp_update_guests_path, method: "patch") do %>
  <hr>
	<% @guests.each do |guest| %>
		<%= fields_for "guests[]", guest do |f| %>
			<% if guest.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>
					<ul>
            <%= guest.errors.full_messages.each { |message| message } %>
					</ul>
				</div>
			<% end %>

      <h3><%= "#{guest.firstname} #{guest.lastname}" %></h3>
      <%= f.hidden_field :firstname %>
      <%= f.hidden_field :lastname %>
      <%= f.hidden_field :responded, value: true %>

      <div class="field">
        <%= f.label :attending, "Will #{guest.firstname} be attending?" %><br>
        <%= f.select :attending, options_for_select([['Yes', 'true'], ['No', 'false']], 'true'), class: 'form-control' %>
        
      </div>

      <div class="field">
        <%= f.label "Dietary Requirements" %><br>
        <%= f.text_area :dietaryreq, class: 'form-control' %>
      </div>

		<% end %>
  <hr>
	<% end %>
  <div class="actions submit-area">
    <%= submit_tag 'Submit RSVP' , class: 'btn btn-default' %>
  </div>
	<% end %>
</div>

app/views/guests/browse_file.html.erb
<h2>Import a guest list</h2>

<%= form_tag guests_import_path, multipart: true do %>
  <%= file_field_tag :file %> 
  <%= submit_tag "Import" %>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/edit_all.html.erb
<%= render 'form_edit_all' %>

app/views/guests/guests_linked.html.erb
<h1>Unlink List</h1>


<%= form_tag(guests_unlink_guests_path, method: "patch") do %>
  <div class="actions">
    <%= submit_tag 'Unlink' , class: 'btn btn-default' %>
  </div>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Unlink?</th>
      </tr>
    </thead>

    <tbody>
    <% @guests.each do |guest| %>
      <%= fields_for "guests[]", guest do |f| %>
        <tr>
          <td><%= guest.firstname %></td>
          <td><%= guest.lastname %></td>
          <td><%= f.check_box :selected, checked: false %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
<% end %>
<br>

app/views/guests/guests_not_linked.html.erb
<h1>Link List</h1>


<%= form_tag(guests_generate_rsvp_path, method: "patch") do %>
  <div class="actions">
    <%= submit_tag 'Link' , class: 'btn btn-default' %>
  </div>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Link</th>
      </tr>
    </thead>

    <tbody>
    <% @guests.each do |guest| %>
      <%= fields_for "guests[]", guest do |f| %>
        <tr>
          <td><%= guest.firstname %></td>
          <td><%= guest.lastname %></td>
          <td><%= f.check_box :selected, checked: false %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
<% end %>
<br>

app/views/guests/import.html.erb
<h2>Import a guest list</h2>

<% form_tag import_guests_path, multipart: true do %>
  <%= file_field_tag :file %> 
  <%= submit_tag "Import" %>
<% end %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guest stats</h1>

<div class='jumbotron'>
  <h4>Number of Guests: <%= @guests.count %></h4>
  <h4>Attending: <%= @guests.attending.count %></h4>
  <h4>Not attending: <%= @guests.not_attending.count %></h4>
  <h4>Responded: <%= @guests.responded.count %></h4>
</div>

<h1>Guest List</h1>

<div>
  <%= link_to 'Download guest list', guests_export_path, class: 'btn btn-default' %>
  <%= link_to 'Upload guest list', guests_browse_file_path, class: 'btn btn-default' %>
  <%= link_to 'Add guest', new_guest_path, class: 'btn btn-default' %>
  <%= link_to 'Link guests', guests_not_linked_path, class: 'btn btn-default' %>
  <%= link_to 'Delete RSVPs from guests', guests_linked_path, class: 'btn btn-default' %>
</div>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Dietary</th>
      <th>Attending</th>
      <th>Responded</th>
      <th>RSVP Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.firstname %></td>
        <td><%= guest.lastname %></td>
        <td><%= guest.responded ? (!guest.dietaryreq.blank?).humanize : '' %></td>
        <td><%= guest.attending.nil? ? '' : guest.attending.humanize %></td>
        <td><%= guest.responded.nil? ? 'No' : guest.responded.humanize %></td>
        <td><%= guest.rsvp ? (link_to guest.rsvp.code, rsvp_guests_path(guest.rsvp.code)) : 'None' %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @guest.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @guest.lastname %>
</p>

<p>
  <strong>Dietaryreq:</strong>
  <%= @guest.dietaryreq %>
</p>

<p>
  <strong>Attending:</strong>
  <%= @guest.attending %>
</p>

<p>
  <strong>RSVP Code:</strong>
  <%= @guest.rsvp.code if @guest.rsvp %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>